'''This is the file where all the reusable queries are'''

'''Institutions'''
CREATE_INSTITUTIONS = """
CREATE TABLE IF NOT EXISTS Institutions(
    INSTID SERIAL PRIMARY KEY,
    OPEID INTEGER NOT NULL,
    UNITID INTEGER NOT NULL,
    ACCREDAGENCY TEXT NOT NULL,
    PREDDEG TEXT NOT NULL,
    HIGHDEG TEXT NOT NULL,
    CONTROL TEXT NOT NULL,
    REGION TEXT NOT NULL,
    UNIQUE (OPEID, UNITID)
);
"""

# --- INSERT ---
INSERT_INSTITUTIONS = """
INSERT INTO Institutions (OPEID, UNITID, ACCREDAGENCY, PREDDEG,
                          HIGHDEG, CONTROL, REGION)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

# --- UPDATE ---
UPDATE_INSTITUTIONS = """
UPDATE Institutions
SET age = ?
WHERE name = ?
"""

'''Financials'''
CREATE_FINANCIALS = """
CREATE TABLE IF NOT EXISTS Financials (
    FINID SERIAL PRIMARY KEY,
    OPEID INTEGER REFERENCES Institutions(OPEID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    TUITIONFEE_IN INTEGER NOT NULL CHECK(TUITIONFEE_IN >= 0),
    TUITIONFEE_OUT INTEGER NOT NULL CHECK(TUITIONFEE_OUT >= 0),
    TUITIONFEE_PROG INTEGER NOT NULL CHECK(TUITIONFEE_PROG >= 0),
    TUITFTE INTEGER NOT NULL CHECK(TUITFTE >= 0),
    AVGFASCAL INTEGER CHECK(AVGFASCAL > 0),
    CDR2 FLOAT CHECK(CDR2 > 0),
    CDR3 FLOAT CHECK(CDR3 > 0),
    UNIQUE (OPEID, YEAR)
);
"""

# --- INSERT ---
INSERT_FINANCIALS = """
INSERT INTO Financials
    (OPEID, YEAR, TUITIONFEE_IN, TUITIONFEE_OUT, TUITIONFEE_PROG,
     TUITFTE, AVGFASCAL, CDR2, CDR3)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# --- UPDATE ---
UPDATE_FINANCIALS = """
UPDATE users
SET age = ?
WHERE name = ?
"""

# --- DELETE ---
DELETE_FINANCIALS = """
DELETE FROM users
WHERE name = ?
"""

'''Academics'''
CREATE_ACADEMICS = """
CREATE TABLE IF NOT EXISTS Academics (
    ACADID SERIAL PRIMARY KEY,
    OPEID INTEGER REFERENCES Institutions(OPEID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    ADM_RATE FLOAT CHECK(ADM_RATE BETWEEN 0 AND 1),
    C100_4 FLOAT CHECK(C100_4 BETWEEN 0 AND 1),
    C100_L4 FLOAT CHECK(C100_L4 BETWEEN 0 AND 1),
    SAT_AVG FLOAT CHECK(SAT_AVG BETWEEN 0 AND 1600),
    COUNT_NWNE_3YR INTEGER CHECK(COUNT_NWNE_3YR >= 0),
    COUNT_WNE_3YR INTEGER CHECK(COUNT_WNE_3YR >= 0),
    CNTOVER150_3YR INTEGER CHECK(CNTOVER150_3YR >= 0),
    UNIQUE (OPEID, YEAR)
);
"""

# --- INSERT ---
INSERT_ACADEMICS = """
INSERT INTO Academics
    (OPEID, YEAR, ADM_RATE, C100_4, C100_L4, SAT_AVG,
     COUNT_NWNE_3YR, COUNT_WNE_3YR, CNTOVER150_3YR)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# --- UPDATE ---
UPDATE_ACADEMICS = """
UPDATE users
SET age = ?
WHERE name = ?
"""

# --- DELETE ---
DELETE_ACADEMICS = """
DELETE FROM users
WHERE name = ?
"""

'''Demographics'''
CREATE_DEMOGRAPHICS = """
CREATE TABLE IF NOT EXISTS Demographics(
    DEMOID SERIAL PRIMARY KEY,
    OPEID INTEGER REFERENCES Institutions(OPEID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    UGDS INTEGER CHECK(UGDS >= 0),
    UGDS_MEN FLOAT CHECK(UGDS_MEN BETWEEN 0 AND 1),
    UGDS_WOMEN FLOAT CHECK(UGDS_WOMEN BETWEEN 0 AND 1),
    UGDS_WHITE FLOAT CHECK(UGDS_WHITE BETWEEN 0 AND 1),
    UGDS_BLACK FLOAT CHECK(UGDS_BLACK BETWEEN 0 AND 1),
    UGDS_HISP FLOAT CHECK(UGDS_HISP BETWEEN 0 AND 1),
    UGDS_ASIAN FLOAT CHECK(UGDS_ASIAN BETWEEN 0 AND 1),
    UGDS_AIAN FLOAT CHECK(UGDS_AIAN BETWEEN 0 AND 1),
    UGDS_NHPI FLOAT CHECK(UGDS_NHPI BETWEEN 0 AND 1),
    UGDS_2MOR FLOAT CHECK(UGDS_2MOR BETWEEN 0 AND 1),
    UGDS_UNKN FLOAT CHECK(UGDS_UNKN BETWEEN 0 AND 1),
    IRPS_MEN FLOAT CHECK(IRPS_MEN BETWEEN 0 AND 1),
    IRPS_WOMEN FLOAT CHECK(IRPS_WOMEN BETWEEN 0 AND 1),
    IRPS_WHITE FLOAT CHECK(IRPS_WHITE BETWEEN 0 AND 1),
    IRPS_BLACK FLOAT CHECK(IRPS_BLACK BETWEEN 0 AND 1),
    IRPS_HISP FLOAT CHECK(IRPS_HISP BETWEEN 0 AND 1),
    IRPS_ASIAN FLOAT CHECK(IRPS_ASIAN BETWEEN 0 AND 1),
    IRPS_AIAN FLOAT CHECK(IRPS_AIAN BETWEEN 0 AND 1),
    IRPS_NHPI FLOAT CHECK(IRPS_NHPI BETWEEN 0 AND 1),
    IRPS_2MOR FLOAT CHECK(IRPS_2MOR BETWEEN 0 AND 1),
    IRPS_UNKN FLOAT CHECK(IRPS_UNKN BETWEEN 0 AND 1),
    UNIQUE (OPEID, YEAR),
    CHECK (ABS(UGDS_WHITE + UGDS_BLACK + UGDS_HISP +
        UGDS_ASIAN + UGDS_AIAN + UGDS_NHPI + UGDS_2MOR + UGDS_UNKN - 1)<0.01),
    CHECK (ABS(IRPS_WHITE + IRPS_BLACK + IRPS_HISP +
        IRPS_ASIAN + IRPS_AIAN + IRPS_NHPI + IRPS_2MOR + IRPS_UNKN - 1)<0.01)
);
"""

# --- INSERT ---
INSERT_DEMOGRAPHICS = """
INSERT INTO Demographics
    (DEMOID, OPEID, YEAR, UGDS, UGDS_MEN, UGDS_WOMEN, UGDS_WHITE, UGDS_BLACK,
     UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR, UGDS_UNKN,
     IRPS_MEN, IRPS_WOMEN, IRPS_WHITE, IRPS_BLACK, IRPS_HISP, IRPS_ASIAN,
     IRPS_AIAN, IRPS_NHPI, IRPS_2MOR, IRPS_UNKN)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# --- UPDATE ---
UPDATE_DEMOGRAPHICS = """
UPDATE users
SET age = ?
WHERE name = ?
"""

# --- DELETE ---
DELETE_DEMOGRAPHICS = """
DELETE FROM users
WHERE name = ?
"""
