'''This is the file where all the reusable queries are'''

'''
Institutions
'''

# --- CREATE ---
CREATE_INSTITUTIONS = """
CREATE TABLE IF NOT EXISTS Institutions(
    UNITID INTEGER PRIMARY KEY,
    OPEID INTEGER NOT NULL,
    ACCREDAGENCY TEXT,
    PREDDEG TEXT,
    HIGHDEG TEXT,
    CONTROL TEXT,
    REGION TEXT,
    LAST_REPORTED INTEGER CHECK (LAST_REPORTED <=
        EXTRACT(YEAR FROM CURRENT_DATE)) NOT NULL,
    LAST_UPDATED TIMESTAMP CHECK (LAST_UPDATED <= NOW()) NOT NULL,
    UNIQUE (OPEID, UNITID)
);
"""

'''Institutions (IPEDS Directory)'''
CREATE_INSTITUTIONS_IPEDS = """
CREATE TABLE IF NOT EXISTS Institutions_IPEDS(
    UNITID INTEGER PRIMARY KEY,
    INSTNM VARCHAR(255) NOT NULL,
    ADDR VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STABBR VARCHAR(10) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    LATITUDE NUMERIC(10,7),
    LONGITUDE NUMERIC(10,7),

    C_BASIC VARCHAR,
    C_IPUG VARCHAR,
    C_UGPRF VARCHAR,
    C_ENPRF VARCHAR,
    C_SZSET VARCHAR,

    COUNTYCD VARCHAR(5),

    CSA VARCHAR(3),
    CBSA VARCHAR(5),

    LAST_REPORTED INTEGER CHECK (LAST_REPORTED <=
        EXTRACT(YEAR FROM CURRENT_DATE)) NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT NOW() CHECK (LAST_UPDATED <= NOW()) NOT NULL
);
"""

# --- INSERT ---

INSERT_INSTITUTIONS = """
INSERT INTO Institutions
    (OPEID, UNITID, ACCREDAGENCY, PREDDEG,
     HIGHDEG, CONTROL, REGION,
     LAST_REPORTED, LAST_UPDATED)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, NOW())
ON CONFLICT (UNITID) DO UPDATE
SET
    OPEID         = EXCLUDED.OPEID,
    ACCREDAGENCY  = EXCLUDED.ACCREDAGENCY,
    PREDDEG       = EXCLUDED.PREDDEG,
    HIGHDEG       = EXCLUDED.HIGHDEG,
    CONTROL       = EXCLUDED.CONTROL,
    REGION        = EXCLUDED.REGION,
    LAST_REPORTED = EXCLUDED.LAST_REPORTED,
    LAST_UPDATED  = CASE
        -- bump LAST_UPDATED only if any "core" fields changed
        WHEN Institutions.OPEID        IS DISTINCT FROM EXCLUDED.OPEID
          OR Institutions.ACCREDAGENCY IS DISTINCT FROM EXCLUDED.ACCREDAGENCY
          OR Institutions.PREDDEG      IS DISTINCT FROM EXCLUDED.PREDDEG
          OR Institutions.HIGHDEG      IS DISTINCT FROM EXCLUDED.HIGHDEG
          OR Institutions.CONTROL      IS DISTINCT FROM EXCLUDED.CONTROL
          OR Institutions.REGION       IS DISTINCT FROM EXCLUDED.REGION
        THEN NOW()
        ELSE Institutions.LAST_UPDATED
    END
WHERE
    -- perform UPDATE if *any* tracked field changed,
    -- including LAST_REPORTED
    Institutions.OPEID         IS DISTINCT FROM EXCLUDED.OPEID
 OR Institutions.ACCREDAGENCY  IS DISTINCT FROM EXCLUDED.ACCREDAGENCY
 OR Institutions.PREDDEG       IS DISTINCT FROM EXCLUDED.PREDDEG
 OR Institutions.HIGHDEG       IS DISTINCT FROM EXCLUDED.HIGHDEG
 OR Institutions.CONTROL       IS DISTINCT FROM EXCLUDED.CONTROL
 OR Institutions.REGION        IS DISTINCT FROM EXCLUDED.REGION
 OR Institutions.LAST_REPORTED IS DISTINCT FROM EXCLUDED.LAST_REPORTED;
"""


INSERT_INSTITUTIONS_IPEDS = """
INSERT INTO Institutions_IPEDS
    (UNITID, INSTNM, ADDR, CITY, STABBR, ZIP,
     LATITUDE, LONGITUDE,
     C_BASIC, C_IPUG, C_UGPRF, C_ENPRF, C_SZSET,
     COUNTYCD, CSA, CBSA,
     LAST_REPORTED, LAST_UPDATED)
VALUES
    (%s, %s, %s, %s, %s, %s,
     %s, %s,
     %s, %s, %s, %s, %s,
     %s, %s, %s,
     %s, NOW())
ON CONFLICT (UNITID) DO UPDATE
SET
    INSTNM     = EXCLUDED.INSTNM,
    ADDR       = EXCLUDED.ADDR,
    CITY       = EXCLUDED.CITY,
    STABBR     = EXCLUDED.STABBR,
    ZIP        = EXCLUDED.ZIP,
    LATITUDE   = EXCLUDED.LATITUDE,
    LONGITUDE  = EXCLUDED.LONGITUDE,
    C_BASIC   = EXCLUDED.C_BASIC,
    C_IPUG    = EXCLUDED.C_IPUG,
    C_UGPRF   = EXCLUDED.C_UGPRF,
    C_ENPRF   = EXCLUDED.C_ENPRF,
    C_SZSET   = EXCLUDED.C_SZSET,
    COUNTYCD = EXCLUDED.COUNTYCD,
    CSA        = EXCLUDED.CSA,
    CBSA       = EXCLUDED.CBSA,
    LAST_REPORTED = EXCLUDED.LAST_REPORTED,
    LAST_UPDATED  = CASE
        WHEN  Institutions_IPEDS.INSTNM     IS DISTINCT FROM EXCLUDED.INSTNM
           OR Institutions_IPEDS.ADDR       IS DISTINCT FROM EXCLUDED.ADDR
           OR Institutions_IPEDS.CITY       IS DISTINCT FROM EXCLUDED.CITY
           OR Institutions_IPEDS.STABBR     IS DISTINCT FROM EXCLUDED.STABBR
           OR Institutions_IPEDS.ZIP        IS DISTINCT FROM EXCLUDED.ZIP
           OR Institutions_IPEDS.LATITUDE   IS DISTINCT FROM EXCLUDED.LATITUDE
           OR Institutions_IPEDS.LONGITUDE  IS DISTINCT FROM EXCLUDED.LONGITUDE
           OR Institutions_IPEDS.C_BASIC   IS DISTINCT FROM EXCLUDED.C_BASIC
           OR Institutions_IPEDS.C_IPUG    IS DISTINCT FROM EXCLUDED.C_IPUG
           OR Institutions_IPEDS.C_UGPRF   IS DISTINCT FROM EXCLUDED.C_UGPRF
           OR Institutions_IPEDS.C_ENPRF   IS DISTINCT FROM EXCLUDED.C_ENPRF
           OR Institutions_IPEDS.C_SZSET   IS DISTINCT FROM EXCLUDED.C_SZSET
           OR Institutions_IPEDS.COUNTYCD IS DISTINCT FROM EXCLUDED.COUNTYCD
           OR Institutions_IPEDS.CSA        IS DISTINCT FROM EXCLUDED.CSA
           OR Institutions_IPEDS.CBSA       IS DISTINCT FROM EXCLUDED.CBSA
        THEN NOW()
        ELSE Institutions_IPEDS.LAST_UPDATED
    END
WHERE
       Institutions_IPEDS.INSTNM     IS DISTINCT FROM EXCLUDED.INSTNM
    OR Institutions_IPEDS.ADDR       IS DISTINCT FROM EXCLUDED.ADDR
    OR Institutions_IPEDS.CITY       IS DISTINCT FROM EXCLUDED.CITY
    OR Institutions_IPEDS.STABBR     IS DISTINCT FROM EXCLUDED.STABBR
    OR Institutions_IPEDS.ZIP        IS DISTINCT FROM EXCLUDED.ZIP
    OR Institutions_IPEDS.LATITUDE   IS DISTINCT FROM EXCLUDED.LATITUDE
    OR Institutions_IPEDS.LONGITUDE  IS DISTINCT FROM EXCLUDED.LONGITUDE
    OR Institutions_IPEDS.C_BASIC   IS DISTINCT FROM EXCLUDED.C_BASIC
    OR Institutions_IPEDS.C_IPUG    IS DISTINCT FROM EXCLUDED.C_IPUG
    OR Institutions_IPEDS.C_UGPRF   IS DISTINCT FROM EXCLUDED.C_UGPRF
    OR Institutions_IPEDS.C_ENPRF   IS DISTINCT FROM EXCLUDED.C_ENPRF
    OR Institutions_IPEDS.C_SZSET   IS DISTINCT FROM EXCLUDED.C_SZSET
    OR Institutions_IPEDS.COUNTYCD IS DISTINCT FROM EXCLUDED.COUNTYCD
    OR Institutions_IPEDS.CSA        IS DISTINCT FROM EXCLUDED.CSA
    OR Institutions_IPEDS.CBSA       IS DISTINCT FROM EXCLUDED.CBSA
    OR Institutions_IPEDS.LAST_REPORTED IS DISTINCT
        FROM EXCLUDED.LAST_REPORTED;
"""

'''
Financials
'''

# --- CREATE ---
CREATE_FINANCIALS = """
CREATE TABLE IF NOT EXISTS Financials (
    UNITID INTEGER REFERENCES Institutions(UNITID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    TUITIONFEE_IN INTEGER CHECK(TUITIONFEE_IN >= 0),
    TUITIONFEE_OUT INTEGER CHECK(TUITIONFEE_OUT >= 0),
    TUITIONFEE_PROG INTEGER CHECK(TUITIONFEE_PROG >= 0),
    TUITFTE INTEGER CHECK(TUITFTE >= 0),
    AVGFASCAL INTEGER CHECK(AVGFASCAL > 0),
    CDR2 FLOAT CHECK(CDR2 >= 0),
    CDR3 FLOAT CHECK(CDR3 >= 0),
    UNIQUE (UNITID, YEAR)
);
"""

# --- INSERT ---
INSERT_FINANCIALS = """
INSERT INTO Financials
    (UNITID, YEAR,
     TUITIONFEE_IN, TUITIONFEE_OUT, TUITIONFEE_PROG,
     TUITFTE, AVGFASCAL, CDR2, CDR3)
VALUES (%s, %s,
        %s, %s, %s,
        %s, %s, %s, %s)
ON CONFLICT (UNITID, YEAR) DO UPDATE
SET
    TUITIONFEE_IN   = EXCLUDED.TUITIONFEE_IN,
    TUITIONFEE_OUT  = EXCLUDED.TUITIONFEE_OUT,
    TUITIONFEE_PROG = EXCLUDED.TUITIONFEE_PROG,
    TUITFTE         = EXCLUDED.TUITFTE,
    AVGFASCAL       = EXCLUDED.AVGFASCAL,
    CDR2            = EXCLUDED.CDR2,
    CDR3            = EXCLUDED.CDR3
"""

'''
Academics
'''

# --- CREATE ---
CREATE_ACADEMICS = """
CREATE TABLE IF NOT EXISTS Academics (
    UNITID INTEGER REFERENCES Institutions(UNITID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    ADM_RATE FLOAT CHECK(ADM_RATE BETWEEN 0 AND 1),
    C100_4 FLOAT CHECK(C100_4 BETWEEN 0 AND 1),
    C100_L4 FLOAT CHECK(C100_L4 BETWEEN 0 AND 1),
    SAT_AVG FLOAT CHECK(SAT_AVG BETWEEN 0 AND 1600),
    COUNT_NWNE_3YR INTEGER CHECK(COUNT_NWNE_3YR >= 0),
    COUNT_WNE_3YR INTEGER CHECK(COUNT_WNE_3YR >= 0),
    CNTOVER150_3YR INTEGER CHECK(CNTOVER150_3YR >= 0),
    UNIQUE (UNITID, YEAR)
);
"""

# --- INSERT ---
INSERT_ACADEMICS = """
INSERT INTO Academics
    (UNITID, YEAR, ADM_RATE, C100_4, C100_L4, SAT_AVG,
     COUNT_NWNE_3YR, COUNT_WNE_3YR, CNTOVER150_3YR)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (UNITID, YEAR) DO UPDATE
SET
    ADM_RATE        = EXCLUDED.ADM_RATE,
    C100_4          = EXCLUDED.C100_4,
    C100_L4         = EXCLUDED.C100_L4,
    SAT_AVG         = EXCLUDED.SAT_AVG,
    COUNT_NWNE_3YR  = EXCLUDED.COUNT_NWNE_3YR,
    COUNT_WNE_3YR   = EXCLUDED.COUNT_WNE_3YR,
    CNTOVER150_3YR  = EXCLUDED.CNTOVER150_3YR
"""

'''
Demographics
'''
# --- CREATE ---
CREATE_DEMOGRAPHICS = """
CREATE TABLE IF NOT EXISTS Demographics(
    UNITID INTEGER REFERENCES Institutions(UNITID),
    YEAR INTEGER CHECK (YEAR <= EXTRACT(YEAR FROM CURRENT_DATE)),
    UGDS INTEGER CHECK(UGDS >= 0),
    UGDS_MEN FLOAT CHECK(UGDS_MEN BETWEEN 0 AND 1),
    UGDS_WOMEN FLOAT CHECK(UGDS_WOMEN BETWEEN 0 AND 1),
    UGDS_WHITE FLOAT CHECK(UGDS_WHITE BETWEEN 0 AND 1),
    UGDS_BLACK FLOAT CHECK(UGDS_BLACK BETWEEN 0 AND 1),
    UGDS_HISP FLOAT CHECK(UGDS_HISP BETWEEN 0 AND 1),
    UGDS_ASIAN FLOAT CHECK(UGDS_ASIAN BETWEEN 0 AND 1),
    UGDS_AIAN FLOAT CHECK(UGDS_AIAN BETWEEN 0 AND 1),
    UGDS_NHPI FLOAT CHECK(UGDS_NHPI BETWEEN 0 AND 1),
    UGDS_2MOR FLOAT CHECK(UGDS_2MOR BETWEEN 0 AND 1),
    UGDS_UNKN FLOAT CHECK(UGDS_UNKN BETWEEN 0 AND 1),
    IRPS_MEN FLOAT CHECK(IRPS_MEN BETWEEN 0 AND 1),
    IRPS_WOMEN FLOAT CHECK(IRPS_WOMEN BETWEEN 0 AND 1),
    IRPS_WHITE FLOAT CHECK(IRPS_WHITE BETWEEN 0 AND 1),
    IRPS_BLACK FLOAT CHECK(IRPS_BLACK BETWEEN 0 AND 1),
    IRPS_HISP FLOAT CHECK(IRPS_HISP BETWEEN 0 AND 1),
    IRPS_ASIAN FLOAT CHECK(IRPS_ASIAN BETWEEN 0 AND 1),
    IRPS_AIAN FLOAT CHECK(IRPS_AIAN BETWEEN 0 AND 1),
    IRPS_NHPI FLOAT CHECK(IRPS_NHPI BETWEEN 0 AND 1),
    IRPS_2MOR FLOAT CHECK(IRPS_2MOR BETWEEN 0 AND 1),
    IRPS_UNKN FLOAT CHECK(IRPS_UNKN BETWEEN 0 AND 1),
    UNIQUE (UNITID, YEAR),
    CHECK (UGDS_WHITE + UGDS_BLACK + UGDS_HISP +
        UGDS_ASIAN + UGDS_AIAN + UGDS_NHPI + UGDS_2MOR + UGDS_UNKN - 1 <0.1),
    CHECK (IRPS_WHITE + IRPS_BLACK + IRPS_HISP +
        IRPS_ASIAN + IRPS_AIAN + IRPS_NHPI + IRPS_2MOR + IRPS_UNKN - 1 <0.1)
);
"""

# --- INSERT ---
INSERT_DEMOGRAPHICS = """
INSERT INTO Demographics
    (UNITID, YEAR,
     UGDS, UGDS_MEN, UGDS_WOMEN, UGDS_WHITE, UGDS_BLACK,
     UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR, UGDS_UNKN,
     IRPS_MEN, IRPS_WOMEN, IRPS_WHITE, IRPS_BLACK, IRPS_HISP, IRPS_ASIAN,
     IRPS_AIAN, IRPS_NHPI, IRPS_2MOR, IRPS_UNKN)
VALUES
    (%s, %s,
     %s, %s, %s, %s, %s,
     %s, %s, %s, %s, %s, %s,
     %s, %s, %s, %s, %s, %s,
     %s, %s, %s, %s)
ON CONFLICT (UNITID, YEAR) DO UPDATE
SET
    DEMOID      = EXCLUDED.DEMOID,
    UGDS        = EXCLUDED.UGDS,
    UGDS_MEN    = EXCLUDED.UGDS_MEN,
    UGDS_WOMEN  = EXCLUDED.UGDS_WOMEN,
    UGDS_WHITE  = EXCLUDED.UGDS_WHITE,
    UGDS_BLACK  = EXCLUDED.UGDS_BLACK,
    UGDS_HISP   = EXCLUDED.UGDS_HISP,
    UGDS_ASIAN  = EXCLUDED.UGDS_ASIAN,
    UGDS_AIAN   = EXCLUDED.UGDS_AIAN,
    UGDS_NHPI   = EXCLUDED.UGDS_NHPI,
    UGDS_2MOR   = EXCLUDED.UGDS_2MOR,
    UGDS_UNKN   = EXCLUDED.UGDS_UNKN,
    IRPS_MEN    = EXCLUDED.IRPS_MEN,
    IRPS_WOMEN  = EXCLUDED.IRPS_WOMEN,
    IRPS_WHITE  = EXCLUDED.IRPS_WHITE,
    IRPS_BLACK  = EXCLUDED.IRPS_BLACK,
    IRPS_HISP   = EXCLUDED.IRPS_HISP,
    IRPS_ASIAN  = EXCLUDED.IRPS_ASIAN,
    IRPS_AIAN   = EXCLUDED.IRPS_AIAN,
    IRPS_NHPI   = EXCLUDED.IRPS_NHPI,
    IRPS_2MOR   = EXCLUDED.IRPS_2MOR,
    IRPS_UNKN   = EXCLUDED.IRPS_UNKN
"""
